"""Markdown export (Obsidian-friendly).

Emoji follow the Obsidian Tasks plugin's syntax so the file stays queryable
there: ⏫/🔼/🔽 priority, 📅 due date, ✅ completion date.
"""
import os
from collections import defaultdict
from datetime import datetime, timezone

from .config import MARKDOWN_PATH
from .db import get_db
from .serialize import tags_by_task

PRIORITY_EMOJI = {"high": "⏫", "medium": "🔼", "low": "🔽"}
STATUS_BOX = {"todo": " ", "doing": "/", "blocked": "!", "done": "x"}


def build_markdown(conn, include_ids=None):
    """Render the whole DB, or just `include_ids`, as Obsidian-flavoured markdown.

    Filtered exports prune categories whose subtree contributed nothing, so a
    one-category export doesn't carry the rest of the tree as empty headings.
    """
    cats = [dict(r) for r in conn.execute(
        "SELECT * FROM categories ORDER BY position, name").fetchall()]
    tasks = [dict(r) for r in conn.execute(
        "SELECT * FROM tasks ORDER BY status = 'done', position, id").fetchall()]
    if include_ids is not None:
        tasks = [t for t in tasks if t["id"] in include_ids]
    tags = tags_by_task(conn)

    children = defaultdict(list)
    for c in cats:
        children[c["parent_id"]].append(c)

    tasks_by_cat = defaultdict(list)
    for t in tasks:
        tasks_by_cat[t["category_id"]].append(t)

    def subtree_has_tasks(cat_id):
        if tasks_by_cat.get(cat_id):
            return True
        return any(subtree_has_tasks(c["id"]) for c in children.get(cat_id, []))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    total = len(tasks)
    open_count = sum(1 for t in tasks if t["status"] != "done")
    lines = [
        "---",
        "title: SenyaTasks",
        "tags: [tasks]",
        f"updated: {now} UTC",
        "---",
        "",
        "# 📋 SenyaTasks",
        "",
        "> [!info] Auto-generated by SenyaTasks — do not edit by hand.",
        f"> Last updated {now} UTC · {open_count} open / {total} total.",
        "",
    ]

    def render_task(t):
        parts = [f"- [{STATUS_BOX.get(t['status'], ' ')}] {t['title']}"]
        parts += [f"#{tag['name']}" for tag in tags.get(t["id"], [])]
        if t["status"] in ("doing", "blocked"):
            parts.append(f"`{t['status']}`")
        parts.append(PRIORITY_EMOJI.get(t["priority"], ""))
        if t["due_date"]:
            parts.append(f"📅 {t['due_date']}")
        if t["completed_at"]:
            parts.append(f"✅ {t['completed_at'][:10]}")
        line = " ".join(p for p in parts if p)
        if t["notes"]:
            line += "\n" + "\n".join(f"    {n}" for n in t["notes"].splitlines())
        return line

    def walk(parent_id, level):
        for c in children.get(parent_id, []):
            if include_ids is not None and not subtree_has_tasks(c["id"]):
                continue
            lines.append(f"{'#' * min(level, 6)} {c['name']}")
            lines.append("")
            ctasks = tasks_by_cat.get(c["id"], [])
            if ctasks:
                lines.extend(render_task(t) for t in ctasks)
                lines.append("")
            walk(c["id"], level + 1)

    walk(None, 2)

    uncategorized = tasks_by_cat.get(None, [])
    if uncategorized:
        lines.append("## Uncategorized")
        lines.append("")
        lines.extend(render_task(t) for t in uncategorized)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_markdown(conn):
    content = build_markdown(conn)
    os.makedirs(os.path.dirname(MARKDOWN_PATH) or ".", exist_ok=True)
    tmp = MARKDOWN_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, MARKDOWN_PATH)  # atomic so Obsidian never sees a partial file


def sync():
    """Call after any mutation to keep Tasks.md in lock-step with the DB."""
    write_markdown(get_db())
