---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

allowedHosts:
  - localhost
  - xps-mint-server
  - xps-mint-server.local

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
