"""The header-driven CSV parser.

The pinned per-bank parsers are a fixed column order and need little proof. This
one infers the layout from the header, which is where the judgement is: which
column names mean what, how a negative is written, and which rows are a
transaction at all. Wealthsimple exports go through it, and Wealthsimple has no
published format — so these pin the behaviour the app depends on rather than
whatever one sample file happened to look like.
"""
import textwrap

import pytest

from finance.ingest.parsers import detect, parse_by_header


@pytest.fixture
def csv_file(tmp_path):
    def write(content, name="wealthsimple-cash.csv"):
        p = tmp_path / name
        p.write_text(textwrap.dedent(content).lstrip())
        return str(p)
    return write


# ---- column mapping --------------------------------------------------------

def test_reads_a_signed_amount_column(csv_file):
    rows = list(parse_by_header(csv_file("""
        date,transaction,description,amount,balance
        2026-03-15,Purchase,TIM HORTONS,-4.85,995.15
        2026-03-16,Deposit,,1000.00,1995.15
    """)))
    assert rows == [
        {"date": "2026-03-15", "merchant": "TIM HORTONS", "amount": 4.85, "direction": "out"},
        {"date": "2026-03-16", "merchant": "Deposit", "amount": 1000.00, "direction": "in"},
    ]


def test_reads_separate_debit_and_credit_columns(csv_file):
    rows = list(parse_by_header(csv_file("""
        Date,Description,Debit,Credit
        2026-03-15,LOBLAWS,142.30,
        2026-03-16,REFUND,,20.00
    """)))
    assert [(r["merchant"], r["amount"], r["direction"]) for r in rows] == [
        ("LOBLAWS", 142.30, "out"), ("REFUND", 20.00, "in")]


def test_column_order_does_not_matter(csv_file):
    """The point of reading the header: exports reorder columns between years."""
    rows = list(parse_by_header(csv_file("""
        amount,payee,settlement date
        -12.50,SPOTIFY,2026-04-02
    """)))
    assert rows == [{"date": "2026-04-02", "merchant": "SPOTIFY", "amount": 12.50, "direction": "out"}]


def test_falls_back_to_the_activity_type_when_description_is_blank(csv_file):
    """Wealthsimple leaves the description empty on funding rows."""
    rows = list(parse_by_header(csv_file("""
        date,transaction,description,amount
        2026-05-01,Contribution,,500.00
    """)))
    assert rows[0]["merchant"] == "Contribution"


def test_unmappable_header_yields_nothing(csv_file):
    assert list(parse_by_header(csv_file("""
        col_a,col_b,col_c
        x,y,z
    """))) == []


# ---- amount formats --------------------------------------------------------

@pytest.mark.parametrize("raw,amount,direction", [
    ("-4.85", 4.85, "out"),
    ("(4.85)", 4.85, "out"),      # accounting-style negative
    ("−4.85", 4.85, "out"),       # unicode minus
    ("-1,240.00", 1240.00, "out"),
    ("$-4.85", 4.85, "out"),
    ("12.40", 12.40, "in"),
    ("12.40 CAD", 12.40, "in"),
])
def test_negative_conventions(csv_file, raw, amount, direction):
    # Quoted, because a thousands separator is a comma inside a CSV field.
    rows = list(parse_by_header(csv_file(f"""
        date,description,amount
        2026-06-01,SHOP,"{raw}"
    """)))
    assert (rows[0]["amount"], rows[0]["direction"]) == (amount, direction)


def test_zero_and_unparseable_amounts_are_skipped(csv_file):
    """A $0 line carries no money and a total row isn't a transaction."""
    rows = list(parse_by_header(csv_file("""
        date,description,amount
        2026-06-01,ADJUSTMENT,0.00
        2026-06-02,NOTES,n/a
        2026-06-03,REAL,-5.00
    """)))
    assert [r["merchant"] for r in rows] == ["REAL"]


# ---- date formats ----------------------------------------------------------

@pytest.mark.parametrize("raw,expected", [
    ("2026-06-01", "2026-06-01"),
    ("2026-06-01T14:22:01Z", "2026-06-01"),   # ISO timestamp keeps only the date
    ("06/01/2026", "2026-06-01"),
    ("Jun 1, 2026", "2026-06-01"),
])
def test_date_formats(csv_file, raw, expected):
    rows = list(parse_by_header(csv_file(f"""
        date,description,amount
        "{raw}",SHOP,-5.00
    """)))
    assert rows[0]["date"] == expected


def test_rows_without_a_usable_date_are_skipped(csv_file):
    """Footers and subtotals sit in the same file as the transactions."""
    rows = list(parse_by_header(csv_file("""
        date,description,amount
        2026-06-01,SHOP,-5.00
        ,Total,-5.00
        Generated by Wealthsimple,,
    """)))
    assert len(rows) == 1


# ---- investment activity ---------------------------------------------------

def test_security_trades_are_prefixed_with_the_activity(csv_file):
    """A trade describes itself by ticker; on its own "AAPL" looks like a shop.

    The prefix is what the default Investments rule matches on, which is what
    keeps a $500 stock purchase out of the spending total.
    """
    rows = list(parse_by_header(csv_file("""
        date,transaction,description,amount
        2026-06-02,Buy,AAPL,-500.00
        2026-06-03,Dividend,VFV,12.40
    """)))
    assert [r["merchant"] for r in rows] == ["Buy AAPL", "Dividend VFV"]


def test_ordinary_purchases_keep_their_merchant_name(csv_file):
    """Prefixing everything would break merchant grouping in the recurring detector."""
    rows = list(parse_by_header(csv_file("""
        date,transaction,description,amount
        2026-06-02,Purchase,NETFLIX.COM,-20.99
    """)))
    assert rows[0]["merchant"] == "NETFLIX.COM"


def test_activity_is_not_prefixed_twice(csv_file):
    rows = list(parse_by_header(csv_file("""
        date,transaction,description,amount
        2026-06-02,Buy,BUY ORDER AAPL,-500.00
    """)))
    assert rows[0]["merchant"] == "BUY ORDER AAPL"


# ---- source routing --------------------------------------------------------

@pytest.mark.parametrize("path,account", [
    ("/import/wealthsimple-cash-2026.csv", "Wealthsimple Cash"),
    ("/import/Wealthsimple/TFSA-activity.csv", "Wealthsimple TFSA"),
    ("/import/wealthsimple_rrsp.csv", "Wealthsimple RRSP"),
    ("/import/wealthsimple-crypto.csv", "Wealthsimple Crypto"),
    # No account keyword in the name: still recognized, as the generic account.
    ("/import/wealthsimple-export.csv", "Wealthsimple Trade"),
])
def test_wealthsimple_files_route_to_the_right_account(path, account):
    assert detect(path).account == account


def test_a_cibc_file_is_not_claimed_by_the_wealthsimple_sources():
    assert detect("/import/cibc-visa-2026.csv").account == "CIBC Visa"
