services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - "gethomepage.dev/enabled=true"
      - "gethomepage.dev/name=Portainer"
      - "gethomepage.dev/group=Docker Containers"
      - "gethomepage.dev/icon=portainer.png"
      - "gethomepage.dev/description=Container manager"
      - "gethomepage.dev/showStats=true"
      - "gethomepage.dev/href=http://192.168.2.100:9000"
      - "gethomepage.dev/widget.type=portainer"
      - "gethomepage.dev/widget.url=http://portainer:9000"
      - "gethomepage.dev/widget.env=1"
      - "gethomepage.dev/widget.key=${PORTAINER_API_KEY}"
    restart: unless-stopped
